sudo: false
language: go
go: [1.12.x, 1.13.x, master]
os: [linux, osx]

git:
  depth: 1

env:
  - GO111MODULE=on
  - GO111MODULE=off

matrix:
  exclude:
    - go: 1.13.x
      env: GO111MODULE=off ## Modules are the default now.

script:
  - go test ./... -v -cover -race

notifications:
  email:
    - dev.rodrigo.lopes@gmail.com